### ISSUE TITLE
Endpoint logowania

### ISSUE THREAD

**Issue by Fuligor** [akai-org/planer-podrozy#22]
Utworzenie endpointu logowania dla użytkowników, który przyjmuje:
- email
- hasło

oraz w przypadku powodzenia zwraca:
- token autoryzacyjny

Informacje techniczne:
- Typ zapytania: POST

**Comment by Fuligor** [comment]
Polecam poczytać sobie trochę o autentykacji w FastAPI-users (https://fastapi-users.github.io/fastapi-users/10.1/configuration/authentication/) i chyba najlepiej na tym etapie projektu będzie użyć Bearer jako transport layer i JWT jako strategii. Natomiast sam endpoint logowania można łatwo wykonać korzystając z tego tutoriala https://fastapi-users.github.io/fastapi-users/10.1/configuration/routers/auth/

**Comment by Maksymilian-Plywaczyk** [comment]
Tak w weekend do tego się zabieram. W razie jakiś wątpliwości będę pisał 👍🏻
