### ISSUE TITLE
Komponent: Map

### ISSUE THREAD

**Issue by marcol13** [akai-org/planer-podrozy#35]
Głównym elementem naszego projektu jest oczywiście mapa. Chcielibyśmy, móc się po niej swobodnie przesuwać i dodawać pinezki. To zadanie skupi się wyłącznie na wyświetleniu takiej mapy za pomocą biblioteki [Leaflet](https://react-leaflet.js.org) i znalezieniu sposobu na ostylowanie jej w podobny sposób jak na makiecie i screenie poniżej. Jest to bardziej skomplikowane zadanie, ale oczywiście służę pomocą 😉

![image](https://user-images.githubusercontent.com/56632321/209880600-24ac7ed8-09e5-4f43-b88f-3d26c1aa425d.png)

**Comment by A-Wodnicki** [comment]
Z tego co widzę to na makiecie tego nie ma ale czy chcemy mieć gdzieś na mapie jakieś przyciski na przykład do zoomowania?
Dałoby się je ostylować żeby pasowały do reszty strony

**Comment by marcol13** [comment]
Pewnie, według mnie to bardzo dobry pomysł!
