### ISSUE TITLE
Deploy aplikacji

### ISSUE THREAD

**Issue by marcol13** [akai-org/planer-podrozy#8]
Deploy aplikacji, np. na [netlify](https://www.netlify.com)

[https://www.youtube.com/watch?v=OPalwvWO63U](https://www.youtube.com/watch?v=OPalwvWO63U)

Opcjonalnie (ale fajnie jakby było) dodać nowy github action, który np. na nowy release wgrywa aktualne pliki z mastera

**Comment by A-Wodnicki** [comment]
Na razie netlify ma tylko dostęp do tych repo kiedy chce je postawić
![obraz](https://user-images.githubusercontent.com/116439661/205034115-51fba645-1976-4e95-8495-36f3b8bc9dd2.png)

W konfiguracji netlify na githubie można jakoś dać ten dostęp ale mi chyba tylko udało się wysłać zapytanie o nadanie dostępu netlify do planera
![obraz](https://user-images.githubusercontent.com/116439661/205034742-3b7b6089-c2b7-456b-9a89-f750afad8f1f.png)

**Comment by A-Wodnicki** [comment]
[Strona](https://akai-guide-me.netlify.app/) jest postawiona
CI powinno działać na netlify z aktualną konfiguracją ale trzeba się przekonać jak wejdą jakieś zmiany do main'a
